theme: jekyll-theme-slate
title: [BitcoinEC]
description: [A minimal patchset on top of Bitcoin Core to provide a stable implementation of Emergent Consensus]
repository_url: https://github.com/bitcoinec/bitcoinec
owner_name: blocktracker
owner_url: https://keybase.io/blocktracker/